apiVersion: batch/v1
kind: Job
metadata:
  # Unique key of the Job instance
  name: geocoder-job
spec:
  backoffLimit: 4
  template:
    metadata:
      name: geocoder-job
      labels:
        jobType: geocoding
        jobNum:  one
    spec:
      imagePullSecrets:
      - name: gcr-json-key
      volumes:
      - name: cloud-storage-key
        secret:
          secretName: gcs-key
      containers:
      - name: geocoder-client
        image: gcr.io/agrc-204220/webapi/geocode-job
        imagePullPolicy: Always
        volumeMounts:
        - name: cloud-storage-key
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        command: ["python"]
        args: ["/tmp/geocode-gcs-csv.py",
               "--apikey", "AGRC-Explorer",
               "--input_bucket", "geocoder-csv-storage-95728",
               "--input_csv", "GeocodeResults_20180925221234.csv",
               "--id_field", "INID",
               "--address_field", "INADDR",
               "--zone_field", "INZONE",
               "--output_bucket", "geocoder-csv-results-98576"]
      # Do not restart containers after they exit
      restartPolicy: Never
