apiVersion: batch/v1
kind: Job
metadata:
  # Unique key of the Job instance
  name: geocoder-job
spec:
  template:
    metadata:
      name: geocoder-job
    spec:
      imagePullSecrets:
      - name: gcr-json-key
      containers:
      - name: geocoder-client
        image: gcr.io/agrc-204220/webapi/geocode-job
        imagePullPolicy: Always
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /tmp/geocode-key.json
        command: ["python"]
        args: ["/tmp/geocode-gcs-csv.py"]
      # Do not restart containers after they exit
      restartPolicy: Never
