apiVersion: batch/v1
kind: Job
metadata:
  # Unique key of the Job instance
  name: geocoder-job-three
spec:
  backoffLimit: 4 # number of retries before throwing error
  template:
    metadata:
      name: geocoder-job-three
      labels:
        jobType: geocoding
        jobNum: three
    spec:
      volumes:
      - name: cloud-storage-key
        secret:
          secretName: gcs-key
      containers:
      - name: geocoder-client
        image: gcr.io/agrc-204220/webapi/geocode-job
        imagePullPolicy: Always
        volumeMounts:
        - name: cloud-storage-key
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        command: ["python"]
        args: ["/tmp/geocode_gcs_csv.py",
               "--apikey", "AGRC-Explorer",
               "--input_bucket", "geocoder-csv-storage-95728",
               "--input_csv", "murray_trash.csv",
               "--id_field", "RESIDENCE_ID",
               "--address_field", "VISTA_ADDRESS",
               "--zone_field", "VISTA_CITY",
               "--output_bucket", "geocoder-csv-results-98576"]
      # Do not restart containers after they exit
      restartPolicy: Never
